import { useState, useRef, useCallback } from 'react';
import {
  Play, Loader2, Sparkles, Clock, Copy, Table, Code,
  ChevronDown, ChevronUp, Trash2, RotateCw,
} from 'lucide-react';
import { toast } from 'sonner';
import { useGraphQuery, useGraphRAGEnhanceQuery } from '../../hooks/useGodMode';
import { cn } from '../../lib/utils';

const TEMPLATES = [
  { label: 'All Nodes', query: 'MATCH (n) RETURN labels(n) AS type, n.name AS name, n.id AS id LIMIT 50' },
  { label: 'All Relationships', query: 'MATCH (a)-[r]->(b) RETURN a.name AS from, type(r) AS rel, b.name AS to LIMIT 50' },
  { label: 'People & Projects', query: 'MATCH (p:Person)-[r]->(proj:Project) RETURN p.name, type(r), proj.name' },
  { label: 'Risks', query: 'MATCH (r:Risk) RETURN r.name, r.content, r.impact, r.status' },
  { label: 'Action Items', query: 'MATCH (a:Action) RETURN a.name, a.task, a.owner, a.status, a.deadline' },
  { label: 'Decisions', query: 'MATCH (d:Decision) RETURN d.name, d.content, d.owner, d.status' },
  { label: 'Node Connections', query: 'MATCH (n)-[r]-(m) WHERE n.name =~ ".*SEARCH.*" RETURN n.name, type(r), m.name LIMIT 30' },
  { label: 'Graph Stats', query: 'MATCH (n) RETURN labels(n)[0] AS type, count(n) AS count ORDER BY count DESC' },
];

type ResultView = 'table' | 'json';

export default function GraphQueryBuilder() {
  const [query, setQuery] = useState('');
  const [resultView, setResultView] = useState<ResultView>('table');
  const [result, setResult] = useState<Record<string, unknown> | null>(null);
  const [history, setHistory] = useState<Array<{ query: string; time: string; success: boolean }>>([]);
  const [showHistory, setShowHistory] = useState(false);
  const [showTemplates, setShowTemplates] = useState(true);
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  const executeQuery = useGraphQuery();
  const enhanceQuery = useGraphRAGEnhanceQuery();

  const handleExecute = useCallback(() => {
    if (!query.trim()) return;
    executeQuery.mutate({ query: query.trim() }, {
      onSuccess: (data) => {
        setResult(data as Record<string, unknown>);
        setHistory(prev => [{ query: query.trim(), time: new Date().toLocaleTimeString(), success: true }, ...prev.slice(0, 19)]);
        toast.success('Query executed');
      },
      onError: () => {
        setHistory(prev => [{ query: query.trim(), time: new Date().toLocaleTimeString(), success: false }, ...prev.slice(0, 19)]);
        toast.error('Query failed');
      },
    });
  }, [query, executeQuery]);

  const handleAIGenerate = useCallback(() => {
    if (!query.trim()) { toast.error('Describe what you want to query'); return; }
    enhanceQuery.mutate({ query: query.trim() }, {
      onSuccess: (data) => {
        const d = data as Record<string, unknown>;
        if (d.cypher) {
          setQuery(String(d.cypher));
          toast.success('Cypher generated by AI');
        }
      },
      onError: () => toast.error('Failed to generate query'),
    });
  }, [query, enhanceQuery]);

  const handleKeyDown = useCallback((e: React.KeyboardEvent) => {
    if ((e.ctrlKey || e.metaKey) && e.key === 'Enter') {
      e.preventDefault();
      handleExecute();
    }
  }, [handleExecute]);

  const resultNodes = (result?.nodes || []) as Array<Record<string, unknown>>;
  const resultEdges = (result?.edges || []) as Array<Record<string, unknown>>;
  const resultRecords = (result?.records || result?.rows || []) as Array<Record<string, unknown>>;
  const columns = resultRecords.length > 0 ? Object.keys(resultRecords[0]) : [];

  return (
    <div className="h-full flex flex-col">
      {/* Templates */}
      <div className="shrink-0 border-b border-gm-border-primary">
        <button onClick={() => setShowTemplates(!showTemplates)} className="w-full flex items-center justify-between px-4 py-2 text-left">
          <span className="text-[10px] font-semibold text-gm-text-tertiary uppercase tracking-wider">Templates</span>
          {showTemplates ? <ChevronUp className="w-3 h-3 text-gm-text-tertiary" /> : <ChevronDown className="w-3 h-3 text-gm-text-tertiary" />}
        </button>
        {showTemplates && (
          <div className="flex gap-1.5 px-4 pb-3 flex-wrap">
            {TEMPLATES.map((t, i) => (
              <button key={i} onClick={() => setQuery(t.query)}
                className="px-2.5 py-1 rounded-lg bg-gm-surface-secondary border border-gm-border-primary text-[10px] text-gm-text-primary hover:bg-gm-surface-hover hover:border-blue-600/30 transition-colors">
                {t.label}
              </button>
            ))}
          </div>
        )}
      </div>

      {/* Editor */}
      <div className="shrink-0 p-4 border-b border-gm-border-primary">
        <div className="relative">
          <textarea ref={textareaRef} value={query} onChange={e => setQuery(e.target.value)} onKeyDown={handleKeyDown}
            rows={4} placeholder="Enter Cypher query... (Ctrl+Enter to execute)\n\nOr describe what you want in natural language, then click AI Generate"
            className="w-full bg-gm-surface-secondary border border-gm-border-primary rounded-xl px-4 py-3 text-xs text-gm-text-primary font-mono leading-relaxed resize-y focus:outline-none focus:ring-2 focus:ring-gm-border-focus placeholder:text-gray-500" />
          <div className="absolute bottom-2 right-2 flex gap-1.5">
            <button onClick={handleAIGenerate} disabled={enhanceQuery.isPending || !query.trim()}
              className="px-2.5 py-1 rounded-lg bg-blue-600/10 text-gm-interactive-primary text-[10px] font-medium hover:bg-blue-600/20 flex items-center gap-1 disabled:opacity-50 transition-colors">
              {enhanceQuery.isPending ? <Loader2 className="w-3 h-3 animate-spin" /> : <Sparkles className="w-3 h-3" />} AI Generate
            </button>
            <button onClick={handleExecute} disabled={executeQuery.isPending || !query.trim()}
              className="px-2.5 py-1 rounded-lg bg-gm-interactive-primary text-gm-text-on-brand text-[10px] font-medium hover:bg-gm-interactive-primary-hover flex items-center gap-1 disabled:opacity-50 transition-colors">
              {executeQuery.isPending ? <Loader2 className="w-3 h-3 animate-spin" /> : <Play className="w-3 h-3" />} Execute
            </button>
          </div>
        </div>
      </div>

      {/* Results */}
      <div className="flex-1 overflow-hidden flex flex-col">
        {result && (
          <>
            <div className="flex items-center justify-between px-4 py-2 border-b border-gm-border-primary shrink-0">
              <div className="flex items-center gap-3 text-[10px] text-gm-text-tertiary">
                {resultRecords.length > 0 && <span>{resultRecords.length} records</span>}
                {resultNodes.length > 0 && <span>{resultNodes.length} nodes</span>}
                {resultEdges.length > 0 && <span>{resultEdges.length} edges</span>}
              </div>
              <div className="flex items-center gap-1">
                <button onClick={() => setResultView('table')} className={cn('p-1 rounded', resultView === 'table' ? 'bg-blue-600/10 text-gm-interactive-primary' : 'text-gm-text-tertiary')}>
                  <Table className="w-3.5 h-3.5" />
                </button>
                <button onClick={() => setResultView('json')} className={cn('p-1 rounded', resultView === 'json' ? 'bg-blue-600/10 text-gm-interactive-primary' : 'text-gm-text-tertiary')}>
                  <Code className="w-3.5 h-3.5" />
                </button>
                <button onClick={() => { navigator.clipboard.writeText(JSON.stringify(result, null, 2)); toast.success('Copied'); }} className="p-1 rounded text-gm-text-tertiary hover:text-gm-text-primary">
                  <Copy className="w-3.5 h-3.5" />
                </button>
              </div>
            </div>
            <div className="flex-1 overflow-auto p-4">
              {resultView === 'table' && resultRecords.length > 0 ? (
                <table className="w-full text-xs">
                  <thead>
                    <tr className="border-b border-gm-border-primary">
                      {columns.map(c => <th key={c} className="py-1.5 px-2 text-left font-medium text-gm-text-tertiary text-[10px] uppercase">{c}</th>)}
                    </tr>
                  </thead>
                  <tbody>
                    {resultRecords.map((row, i) => (
                      <tr key={i} className="border-b border-[var(--gm-border-primary)] hover:bg-[var(--gm-surface-hover)]">
                        {columns.map(c => (
                          <td key={c} className="py-1.5 px-2 text-gm-text-primary max-w-[200px] truncate">
                            {typeof row[c] === 'object' ? JSON.stringify(row[c]) : String(row[c] ?? '')}
                          </td>
                        ))}
                      </tr>
                    ))}
                  </tbody>
                </table>
              ) : resultView === 'json' || resultRecords.length === 0 ? (
                <pre className="text-[10px] text-gm-text-primary font-mono whitespace-pre-wrap leading-relaxed">{JSON.stringify(result, null, 2)}</pre>
              ) : null}
            </div>
          </>
        )}
        {!result && (
          <div className="flex-1 flex items-center justify-center text-gm-text-tertiary">
            <div className="text-center">
              <Code className="w-10 h-10 mx-auto mb-3 text-gray-600" />
              <p className="text-xs">Write a Cypher query or use a template above</p>
              <p className="text-[10px] text-gray-400 mt-1">Ctrl+Enter to execute</p>
            </div>
          </div>
        )}
      </div>

      {/* History */}
      {history.length > 0 && (
        <div className="shrink-0 border-t border-gm-border-primary">
          <button onClick={() => setShowHistory(!showHistory)} className="w-full flex items-center justify-between px-4 py-2">
            <span className="text-[10px] font-semibold text-gm-text-tertiary uppercase tracking-wider flex items-center gap-1">
              <Clock className="w-3 h-3" /> History ({history.length})
            </span>
            {showHistory ? <ChevronUp className="w-3 h-3 text-gm-text-tertiary" /> : <ChevronDown className="w-3 h-3 text-gm-text-tertiary" />}
          </button>
          {showHistory && (
            <div className="px-4 pb-3 max-h-32 overflow-y-auto space-y-1">
              {history.map((h, i) => (
                <button key={i} onClick={() => setQuery(h.query)} className="w-full text-left flex items-center gap-2 px-2 py-1 rounded hover:bg-gm-surface-secondary transition-colors">
                  <div className={cn('w-1.5 h-1.5 rounded-full shrink-0', h.success ? 'bg-gm-status-success' : 'bg-gm-status-danger')} />
                  <span className="text-[10px] text-gm-text-primary font-mono truncate flex-1">{h.query}</span>
                  <span className="text-[10px] text-gm-text-tertiary shrink-0">{h.time}</span>
                </button>
              ))}
            </div>
          )}
        </div>
      )}
    </div>
  );
}
